/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista;

/**
 *
 * @author Alumno
 */
public class AccesoADatos extends javax.swing.JDialog {

    /**
     * Creates new form AccesoADatos
     */
    public AccesoADatos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        img_logo1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        roundButton1 = new vista.RoundButton();
        roundButton2 = new vista.RoundButton();
        roundButton3 = new vista.RoundButton();
        roundButton4 = new vista.RoundButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        roundButton5 = new vista.RoundButton();
        roundButton6 = new vista.RoundButton();
        roundButton7 = new vista.RoundButton();
        roundButton8 = new vista.RoundButton();
        roundButton9 = new vista.RoundButton();
        roundButton10 = new vista.RoundButton();
        roundButton11 = new vista.RoundButton();
        roundButton12 = new vista.RoundButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 832));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 98, 173));
        jPanel1.setPreferredSize(new java.awt.Dimension(350, 832));

        img_logo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/EtiquetaRiojaRecurso 3x1.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("AcademIQ");

        roundButton1.setForeground(new java.awt.Color(0, 98, 173));
        roundButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/HomeIcono.png"))); // NOI18N
        roundButton1.setText("  INICIO");
        roundButton1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        roundButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        roundButton1.setRound(15);

        roundButton2.setBackground(new java.awt.Color(0, 98, 173));
        roundButton2.setForeground(new java.awt.Color(255, 255, 255));
        roundButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/NotasIcono.png"))); // NOI18N
        roundButton2.setText("  NOTAS");
        roundButton2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        roundButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        roundButton2.setRound(15);

        roundButton3.setBackground(new java.awt.Color(0, 98, 173));
        roundButton3.setForeground(new java.awt.Color(255, 255, 255));
        roundButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/AjustesIcono.png"))); // NOI18N
        roundButton3.setText("  AJUSTES");
        roundButton3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        roundButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        roundButton3.setRound(15);

        roundButton4.setBackground(new java.awt.Color(0, 98, 173));
        roundButton4.setForeground(new java.awt.Color(255, 255, 255));
        roundButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CalendarioIcono.png"))); // NOI18N
        roundButton4.setText("  CALENDARIO");
        roundButton4.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        roundButton4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        roundButton4.setRound(15);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(img_logo1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE))
                    .addComponent(jSeparator1)
                    .addComponent(roundButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(roundButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(roundButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(roundButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(img_logo1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(roundButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(roundButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(roundButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(roundButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(481, 481, 481))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 350, 832);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("Acceso A Datos");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(40, 50, 622, 72);

        roundButton5.setBackground(new java.awt.Color(153, 153, 153));
        roundButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Usuario.png"))); // NOI18N
        roundButton5.setRound(110);
        jPanel2.add(roundButton5);
        roundButton5.setBounds(800, 30, 90, 90);

        roundButton6.setBackground(new java.awt.Color(0, 98, 173));
        roundButton6.setForeground(new java.awt.Color(255, 255, 255));
        roundButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CalendarioIcono.png"))); // NOI18N
        roundButton6.setText("  CALENDARIO");
        roundButton6.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        roundButton6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        roundButton6.setRound(15);
        jPanel2.add(roundButton6);
        roundButton6.setBounds(30, 620, 870, 80);

        roundButton7.setBackground(new java.awt.Color(0, 98, 173));
        roundButton7.setForeground(new java.awt.Color(255, 255, 255));
        roundButton7.setText("Tema 1: Fundamentos de la programacion");
        roundButton7.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        roundButton7.setRound(15);
        jPanel2.add(roundButton7);
        roundButton7.setBounds(30, 140, 870, 80);

        roundButton8.setBackground(new java.awt.Color(0, 98, 173));
        roundButton8.setForeground(new java.awt.Color(255, 255, 255));
        roundButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CalendarioIcono.png"))); // NOI18N
        roundButton8.setText("  CALENDARIO");
        roundButton8.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        roundButton8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        roundButton8.setRound(15);
        jPanel2.add(roundButton8);
        roundButton8.setBounds(30, 220, 870, 80);

        roundButton9.setBackground(new java.awt.Color(0, 98, 173));
        roundButton9.setForeground(new java.awt.Color(255, 255, 255));
        roundButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CalendarioIcono.png"))); // NOI18N
        roundButton9.setText("  CALENDARIO");
        roundButton9.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        roundButton9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        roundButton9.setRound(15);
        jPanel2.add(roundButton9);
        roundButton9.setBounds(30, 300, 870, 80);

        roundButton10.setBackground(new java.awt.Color(0, 98, 173));
        roundButton10.setForeground(new java.awt.Color(255, 255, 255));
        roundButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CalendarioIcono.png"))); // NOI18N
        roundButton10.setText("  CALENDARIO");
        roundButton10.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        roundButton10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        roundButton10.setRound(15);
        jPanel2.add(roundButton10);
        roundButton10.setBounds(30, 380, 870, 80);

        roundButton11.setBackground(new java.awt.Color(0, 98, 173));
        roundButton11.setForeground(new java.awt.Color(255, 255, 255));
        roundButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CalendarioIcono.png"))); // NOI18N
        roundButton11.setText("  CALENDARIO");
        roundButton11.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        roundButton11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        roundButton11.setRound(15);
        jPanel2.add(roundButton11);
        roundButton11.setBounds(30, 460, 870, 80);

        roundButton12.setBackground(new java.awt.Color(0, 98, 173));
        roundButton12.setForeground(new java.awt.Color(255, 255, 255));
        roundButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CalendarioIcono.png"))); // NOI18N
        roundButton12.setText("  CALENDARIO");
        roundButton12.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        roundButton12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        roundButton12.setRound(15);
        jPanel2.add(roundButton12);
        roundButton12.setBounds(30, 540, 870, 80);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(350, 0, 930, 830);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccesoADatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccesoADatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccesoADatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccesoADatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AccesoADatos dialog = new AccesoADatos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel img_logo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private vista.RoundButton roundButton1;
    private vista.RoundButton roundButton10;
    private vista.RoundButton roundButton11;
    private vista.RoundButton roundButton12;
    private vista.RoundButton roundButton2;
    private vista.RoundButton roundButton3;
    private vista.RoundButton roundButton4;
    private vista.RoundButton roundButton5;
    private vista.RoundButton roundButton6;
    private vista.RoundButton roundButton7;
    private vista.RoundButton roundButton8;
    private vista.RoundButton roundButton9;
    // End of variables declaration//GEN-END:variables
}
