/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista;

/**
 *
 * @author Alumno
 */
public class InicioApp extends javax.swing.JDialog {
    
    AccesoADatos accesoADatos;
    SistemasDeGestion sistemas;

    /**
     * Creates new form InicioApp
     */
    public InicioApp(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        img_logo1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        roundButton1 = new vista.RoundButton();
        roundButton2 = new vista.RoundButton();
        roundButton3 = new vista.RoundButton();
        roundButton4 = new vista.RoundButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        roundButton5 = new vista.RoundButton();
        btn_programacion = new javax.swing.JButton();
        btn_accesoADatos = new javax.swing.JButton();
        btn_desarrollo = new javax.swing.JButton();
        btn_sistemasGestion = new javax.swing.JButton();
        btn_psp = new javax.swing.JButton();
        btn_empresa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1280, 832));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 98, 173));
        jPanel1.setPreferredSize(new java.awt.Dimension(350, 832));

        img_logo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/EtiquetaRiojaRecurso 3x1.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("AcademIQ");

        roundButton1.setForeground(new java.awt.Color(0, 98, 173));
        roundButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/HomeIcono.png"))); // NOI18N
        roundButton1.setText("  INICIO");
        roundButton1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        roundButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        roundButton1.setRound(15);

        roundButton2.setBackground(new java.awt.Color(0, 98, 173));
        roundButton2.setForeground(new java.awt.Color(255, 255, 255));
        roundButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/NotasIcono.png"))); // NOI18N
        roundButton2.setText("  NOTAS");
        roundButton2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        roundButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        roundButton2.setRound(15);

        roundButton3.setBackground(new java.awt.Color(0, 98, 173));
        roundButton3.setForeground(new java.awt.Color(255, 255, 255));
        roundButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/AjustesIcono.png"))); // NOI18N
        roundButton3.setText("  AJUSTES");
        roundButton3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        roundButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        roundButton3.setRound(15);

        roundButton4.setBackground(new java.awt.Color(0, 98, 173));
        roundButton4.setForeground(new java.awt.Color(255, 255, 255));
        roundButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CalendarioIcono.png"))); // NOI18N
        roundButton4.setText("  CALENDARIO");
        roundButton4.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        roundButton4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        roundButton4.setRound(15);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(img_logo1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE))
                    .addComponent(jSeparator1)
                    .addComponent(roundButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(roundButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(roundButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(roundButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(img_logo1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(roundButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(roundButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(roundButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(roundButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(481, 481, 481))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 350, 832);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("¡Hola de nuevo, nombre!");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(40, 50, 622, 72);

        roundButton5.setBackground(new java.awt.Color(153, 153, 153));
        roundButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Usuario.png"))); // NOI18N
        roundButton5.setRound(110);
        jPanel2.add(roundButton5);
        roundButton5.setBounds(800, 30, 90, 90);

        btn_programacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ProgramacionMultimedia.png"))); // NOI18N
        btn_programacion.setBorder(null);
        btn_programacion.setContentAreaFilled(false);
        jPanel2.add(btn_programacion);
        btn_programacion.setBounds(620, 140, 270, 210);

        btn_accesoADatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/accesoADatos.png"))); // NOI18N
        btn_accesoADatos.setBorder(null);
        btn_accesoADatos.setContentAreaFilled(false);
        btn_accesoADatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_accesoADatosActionPerformed(evt);
            }
        });
        jPanel2.add(btn_accesoADatos);
        btn_accesoADatos.setBounds(20, 140, 270, 210);

        btn_desarrollo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/DesarrolloInterfaces.png"))); // NOI18N
        btn_desarrollo.setBorder(null);
        btn_desarrollo.setBorderPainted(false);
        btn_desarrollo.setContentAreaFilled(false);
        jPanel2.add(btn_desarrollo);
        btn_desarrollo.setBounds(320, 140, 270, 210);

        btn_sistemasGestion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/SistemaGestion.png"))); // NOI18N
        btn_sistemasGestion.setBorder(null);
        btn_sistemasGestion.setContentAreaFilled(false);
        btn_sistemasGestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sistemasGestionActionPerformed(evt);
            }
        });
        jPanel2.add(btn_sistemasGestion);
        btn_sistemasGestion.setBounds(20, 370, 270, 210);

        btn_psp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/PSP.png"))); // NOI18N
        btn_psp.setBorder(null);
        btn_psp.setContentAreaFilled(false);
        jPanel2.add(btn_psp);
        btn_psp.setBounds(320, 370, 270, 210);

        btn_empresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Empresa.png"))); // NOI18N
        btn_empresa.setBorder(null);
        btn_empresa.setContentAreaFilled(false);
        jPanel2.add(btn_empresa);
        btn_empresa.setBounds(620, 370, 270, 210);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(350, 0, 930, 830);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_accesoADatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_accesoADatosActionPerformed
        this.dispose();
        accesoADatos = new AccesoADatos(this, true);
        accesoADatos.setVisible(true);
    }//GEN-LAST:event_btn_accesoADatosActionPerformed

    private void btn_sistemasGestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sistemasGestionActionPerformed
        this.dispose();
        sistemas = new SistemasDeGestion(this, true);
        sistemas.setVisible(true);
    }//GEN-LAST:event_btn_sistemasGestionActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_accesoADatos;
    private javax.swing.JButton btn_desarrollo;
    private javax.swing.JButton btn_empresa;
    private javax.swing.JButton btn_programacion;
    private javax.swing.JButton btn_psp;
    private javax.swing.JButton btn_sistemasGestion;
    private javax.swing.JLabel img_logo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private vista.RoundButton roundButton1;
    private vista.RoundButton roundButton2;
    private vista.RoundButton roundButton3;
    private vista.RoundButton roundButton4;
    private vista.RoundButton roundButton5;
    // End of variables declaration//GEN-END:variables
}
