/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista;

import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author Alumno
 */
public class Notas extends javax.swing.JDialog {

    /**
     * Creates new form Notas
     */
    public Notas(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        img_logo1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        btn_inicio = new vista.RoundButton();
        btn_notas = new vista.RoundButton();
        btn_ajustes = new vista.RoundButton();
        btn_calendario = new vista.RoundButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        roundButton5 = new vista.RoundButton();
        btn_Trimestre1 = new vista.RoundButton();
        btn_Trimestre2 = new vista.RoundButton();
        btn_Trimestre3 = new vista.RoundButton();
        btn_Global = new vista.RoundButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Notas");
        setMaximumSize(new java.awt.Dimension(1280, 832));
        setMinimumSize(new java.awt.Dimension(1280, 832));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 98, 173));
        jPanel1.setPreferredSize(new java.awt.Dimension(350, 832));

        img_logo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/EtiquetaRiojaRecurso 3x1.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("AcademIQ");

        btn_inicio.setBackground(new java.awt.Color(0, 98, 173));
        btn_inicio.setForeground(new java.awt.Color(255, 255, 255));
        btn_inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/home_blanco.png"))); // NOI18N
        btn_inicio.setText("  INICIO");
        btn_inicio.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btn_inicio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_inicio.setRound(15);
        btn_inicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_inicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_inicioMouseExited(evt);
            }
        });
        btn_inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inicioActionPerformed(evt);
            }
        });

        btn_notas.setForeground(new java.awt.Color(0, 98, 173));
        btn_notas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/notas_color.png"))); // NOI18N
        btn_notas.setText("  NOTAS");
        btn_notas.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btn_notas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_notas.setRound(15);
        btn_notas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_notasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_notasMouseExited(evt);
            }
        });

        btn_ajustes.setBackground(new java.awt.Color(0, 98, 173));
        btn_ajustes.setForeground(new java.awt.Color(255, 255, 255));
        btn_ajustes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/AjustesIcono.png"))); // NOI18N
        btn_ajustes.setText("  AJUSTES");
        btn_ajustes.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btn_ajustes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_ajustes.setRound(15);
        btn_ajustes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_ajustesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_ajustesMouseExited(evt);
            }
        });

        btn_calendario.setBackground(new java.awt.Color(0, 98, 173));
        btn_calendario.setForeground(new java.awt.Color(255, 255, 255));
        btn_calendario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CalendarioIcono.png"))); // NOI18N
        btn_calendario.setText("  CALENDARIO");
        btn_calendario.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btn_calendario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_calendario.setRound(15);
        btn_calendario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_calendarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_calendarioMouseExited(evt);
            }
        });
        btn_calendario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calendarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(img_logo1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE))
                    .addComponent(jSeparator1)
                    .addComponent(btn_inicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_notas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_ajustes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_calendario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(img_logo1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_calendario, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_notas, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_ajustes, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(481, 481, 481))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 350, 832);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 98, 173));
        jLabel2.setText("Calificaciones");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(340, 40, 230, 72);

        roundButton5.setBackground(new java.awt.Color(153, 153, 153));
        roundButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Usuario.png"))); // NOI18N
        roundButton5.setRound(110);
        jPanel2.add(roundButton5);
        roundButton5.setBounds(800, 30, 90, 90);

        btn_Trimestre1.setBackground(new java.awt.Color(0, 98, 173));
        btn_Trimestre1.setForeground(new java.awt.Color(255, 255, 255));
        btn_Trimestre1.setText("Trimestre 3");
        btn_Trimestre1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btn_Trimestre1.setHideActionText(true);
        btn_Trimestre1.setRound(15);
        btn_Trimestre1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_Trimestre1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_Trimestre1MouseExited(evt);
            }
        });
        btn_Trimestre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Trimestre1ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Trimestre1);
        btn_Trimestre1.setBounds(470, 140, 133, 52);

        btn_Trimestre2.setBackground(new java.awt.Color(0, 98, 173));
        btn_Trimestre2.setForeground(new java.awt.Color(255, 255, 255));
        btn_Trimestre2.setText("Trimestre 1");
        btn_Trimestre2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btn_Trimestre2.setRound(15);
        btn_Trimestre2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_Trimestre2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_Trimestre2MouseExited(evt);
            }
        });
        btn_Trimestre2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Trimestre2ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Trimestre2);
        btn_Trimestre2.setBounds(70, 140, 133, 52);

        btn_Trimestre3.setBackground(new java.awt.Color(0, 98, 173));
        btn_Trimestre3.setForeground(new java.awt.Color(255, 255, 255));
        btn_Trimestre3.setText("Nota Global");
        btn_Trimestre3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btn_Trimestre3.setRound(15);
        btn_Trimestre3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_Trimestre3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_Trimestre3MouseExited(evt);
            }
        });
        btn_Trimestre3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Trimestre3ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Trimestre3);
        btn_Trimestre3.setBounds(670, 140, 138, 52);

        btn_Global.setBackground(new java.awt.Color(0, 98, 173));
        btn_Global.setForeground(new java.awt.Color(255, 255, 255));
        btn_Global.setText("Trimestre 2");
        btn_Global.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btn_Global.setRound(15);
        btn_Global.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_GlobalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_GlobalMouseExited(evt);
            }
        });
        btn_Global.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GlobalActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Global);
        btn_Global.setBounds(270, 140, 133, 52);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(350, 0, 930, 830);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_notasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_notasMouseEntered

    }//GEN-LAST:event_btn_notasMouseEntered

    private void btn_notasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_notasMouseExited

    }//GEN-LAST:event_btn_notasMouseExited

    private void btn_ajustesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ajustesMouseEntered
        btn_ajustes.setBackground(Color.WHITE);
        btn_ajustes.setForeground(new Color(0, 98, 173));
        btn_ajustes.setIcon(new ImageIcon(getClass().getResource("/imagenes/ajustes_color.png")));
    }//GEN-LAST:event_btn_ajustesMouseEntered

    private void btn_ajustesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ajustesMouseExited
        btn_ajustes.setBackground(new Color(0, 98, 173));
        btn_ajustes.setForeground(Color.WHITE);
        btn_ajustes.setIcon(new ImageIcon(getClass().getResource("/imagenes/AjustesIcono.png")));

    }//GEN-LAST:event_btn_ajustesMouseExited

    private void btn_calendarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_calendarioMouseEntered
        btn_calendario.setBackground(Color.WHITE);
        btn_calendario.setForeground(new Color(0, 98, 173));
        btn_calendario.setIcon(new ImageIcon(getClass().getResource("/imagenes/calendario_color.png")));

    }//GEN-LAST:event_btn_calendarioMouseEntered

    private void btn_calendarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_calendarioMouseExited
        btn_calendario.setBackground(new Color(0, 98, 173));
        btn_calendario.setForeground(Color.WHITE);
        btn_calendario.setIcon(new ImageIcon(getClass().getResource("/imagenes/CalendarioIcono.png")));
    }//GEN-LAST:event_btn_calendarioMouseExited

    private void btn_calendarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calendarioActionPerformed
        this.dispose();
        Calendario calendario = new Calendario(this, true);
        calendario.setVisible(true);
    }//GEN-LAST:event_btn_calendarioActionPerformed

    private void btn_inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inicioActionPerformed
        this.dispose();
        InicioApp inicio = new InicioApp(null, true);
        inicio.setVisible(true);
    }//GEN-LAST:event_btn_inicioActionPerformed

    private void btn_inicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_inicioMouseEntered
        btn_inicio.setBackground(Color.WHITE);
        btn_inicio.setForeground(new Color(0, 98, 173));
        btn_inicio.setIcon(new ImageIcon(getClass().getResource("/imagenes/HomeIcono.png")));
    }//GEN-LAST:event_btn_inicioMouseEntered

    private void btn_inicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_inicioMouseExited
        btn_inicio.setBackground(new Color(0, 98, 173));
        btn_inicio.setForeground(Color.WHITE);
        btn_inicio.setIcon(new ImageIcon(getClass().getResource("/imagenes/home_blanco.png")));
    }//GEN-LAST:event_btn_inicioMouseExited

    private void btn_Trimestre1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Trimestre1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Trimestre1MouseEntered

    private void btn_Trimestre1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Trimestre1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Trimestre1MouseExited

    private void btn_Trimestre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Trimestre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Trimestre1ActionPerformed

    private void btn_Trimestre2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Trimestre2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Trimestre2MouseEntered

    private void btn_Trimestre2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Trimestre2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Trimestre2MouseExited

    private void btn_Trimestre2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Trimestre2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Trimestre2ActionPerformed

    private void btn_Trimestre3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Trimestre3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Trimestre3MouseEntered

    private void btn_Trimestre3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Trimestre3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Trimestre3MouseExited

    private void btn_Trimestre3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Trimestre3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Trimestre3ActionPerformed

    private void btn_GlobalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_GlobalMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_GlobalMouseEntered

    private void btn_GlobalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_GlobalMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_GlobalMouseExited

    private void btn_GlobalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GlobalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_GlobalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private vista.RoundButton btn_Global;
    private vista.RoundButton btn_Trimestre1;
    private vista.RoundButton btn_Trimestre2;
    private vista.RoundButton btn_Trimestre3;
    private vista.RoundButton btn_ajustes;
    private vista.RoundButton btn_calendario;
    private vista.RoundButton btn_inicio;
    private vista.RoundButton btn_notas;
    private javax.swing.JLabel img_logo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private vista.RoundButton roundButton5;
    // End of variables declaration//GEN-END:variables
}
